######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 29 17:39:25 2015
######################################################################

TEMPLATE = app
TARGET = IGP
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h Pattern.h Renderer.h
SOURCES += main.cpp MainWindow.cpp Pattern.cpp Renderer.cpp
