######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 31 18:48:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h Pattern.h Renderer.h ResizeDialog.h
SOURCES += main.cpp MainWindow.cpp Pattern.cpp Renderer.cpp ResizeDialog.cpp
